substitutions:
  devicename: roode-home-single
  friendly_name: Roode Home Single
  sensor_profile: single
  sensor_count: "1"

external_components:
  refresh: always
  source: components

packages:
  base: !include esphome/packages/home-base.yaml
  primary: !include
    file: esphome/packages/roode-node.yaml
    vars:
      node_key: primary
      node_label: Primary
      node_address: "0x2A"
      node_xshut_pin: GPIO16
