substitutions:
  devicename: roode-six-sensor-bringup-v3
  friendly_name: Roode Six Sensor Bring-up V3
  sensor_profile: six_sensor_board_test_v3
  expected_sensor_count: "6"

packages:
  bringup: !include peopleCounter32SixSensorBringup.yaml
